# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18GoCBmM3nkLMV6UzNDx2r5Z-_sSV_z_I
"""

import pandas as pd

titanic= pd.read_excel('https://github.com/YBI-Foundation/Dataset/raw/main/Titanic.xlsx')

titanic.info()

titanic.head()

titanic.describe()